name: Automated checks

on:
  pull_request:
    branches:
      - main
  push:
    - main

jobs:
  - name: Run lint
    uses: ./.github/workflows/run_lint.yml
  - name: Run formatting
    needs: Run lint
    uses: ./.github/workflows/run_format.yml
  - name: Run tests
    needs: Run formatting
    uses: ./.github/workflows/run_tests.yml
