name: Automated checks

on:
  pull_request:
    branches:
      - main
  branches:
    branches:
      - main

jobs:
  - name: Run tests
    uses: ./.github/workflows/run_tests.yml
  - name: Run lint
    needs: Run tests
    uses: ./.github/workflows/run_lint.yml
  - name: Run formatting
    needs: Run lint
    uses: ./.github/workflows/run_format.yml
