name: Check for Changes

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      compare_branch:
        required: true
        type: string
    outputs:
      has_changes:
        description: 'Whether there are changes between the branches'
        value: ${{ jobs.check_diff.outputs.has_changes }}

jobs:
  check_diff:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for changes between branches
        id: check_diff
        run: |
          # Fetch all branches
          git fetch origin

          # Check if base branch exists remotely
          if git show-ref --verify --quiet refs/remotes/origin/${{ inputs.base_branch }}; then
            echo "Base branch ${{ inputs.base_branch }} exists, comparing with ${{ inputs.compare_branch }}"
            if git diff --quiet origin/${{ inputs.base_branch }}..origin/${{ inputs.compare_branch }}; then
              echo "has_changes=false" >> $GITHUB_OUTPUT
              echo "No changes detected between branches"
            else
              echo "has_changes=true" >> $GITHUB_OUTPUT
              echo "Changes detected between branches"
            fi
          else
            echo "Base branch ${{ inputs.base_branch }} does not exist, assuming changes needed"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
